### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by benjaminkomen** [joshlong/spring-boot-and-java-10#1]
How did you get this to work with java 10? I get the following error:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project XXX: Fatal error compiling: invalid target release: 10 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project XXX: Fatal error compiling

**Comment by anandshah123** [comment]
Initial pointers. Make sure you are running using `Java 10 ` and also have [latest](https://maven.apache.org/download.cgi) maven version

**Comment by axpira** [comment]
I have the same error:
![error](https://user-images.githubusercontent.com/1330080/42243943-5f316f6c-7ee9-11e8-9528-60d14af3cfab.png)

**Comment by anandshah123** [comment]
@axpira I can see your maven running on jdk 1.8.0_151

**Comment by mballoni** [comment]
I created a PR that fixes it:
https://github.com/joshlong/spring-boot-and-java-10/pull/3

**Comment by benjaminkomen** [comment]
@anandshah123 So the solution is to run maven on jdk 10? How do I do that?
@mballoni Your PR doesn't fix the problem for me, possibly because I need to change the JAVA_HOME or maven java version to java 10?

Oooh, wait I got it. What I was trying to do, and did not succeed in doing, was the command `mvn clean install`.
But if I just run the application (e.g. from IntelliJ clicking the Run button in the DemoApplication file), it does indeed work!

So I guess I can close this issue.
